name: lissen_mvp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6

  cupertino_icons: ^1.0.8
  video_player: ^2.8.2

  # --------------------------
  # Firebase (compatibles entre sÃ­)
  # --------------------------
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.3
  cloud_functions: ^5.1.3
  flutter_stripe: ^11.1.0
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.1
  zego_zimkit: ^1.8.2
  zego_uikit_prebuilt_call: ^4.10.0

  # --------------------------
  # Plugins adicionales
  # --------------------------
  image_picker: ^1.2.1
  geolocator: ^12.0.0
  just_audio: ^0.9.36
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0

  # --------------------------
  # ðŸ”µ Login Social
  # --------------------------
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

  # ðŸ”µ Botones oficiales (UI)
  sign_in_button: ^4.0.1   # ðŸ‘ˆ SOLO CAMBIÃ‰ ESTA VERSIÃ“N

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/offer_request.wav
